/**
 * Agent briefing renderer (round-2, the promoted hand-written artifact)
 *
 * Round 1's revealed workflow is human-triages-agent-executes: the
 * maintainer's real output was a triage — real / noise / decision — plus
 * an execution order, hand-packaged for a planning agent. This module is
 * that packaging, automated. The human still makes every decision (the
 * briefing carries verdict commands, it never files them); alarm-only is
 * intact.
 *
 * Written to .vibecheck/out/agent-briefing.md on every run, and
 * regenerated by `vibecheck triage` after verdicts land.
 */

import type { AuditRunResult } from "./index.js";
import type { FileScore } from "./scoring.js";

function laneAction(
  result: AuditRunResult,
  lane: string,
  path: string,
): string {
  switch (lane) {
    case "size":
      return "split along responsibility boundaries; add a test before moving logic";
    case "arrival":
      return "add at least one test whose import path reaches this file before changing it further";
    case "deadcode": {
      const entry = result.lanes.deadcode?.entries.find((e) => e.path === path);
      return entry?.unusedFile
        ? "verify unreferenced repo-wide (string imports, dynamic loading), then delete the file"
        : "verify each flagged export is unconsumed, then delete it";
    }
    case "duplication":
      return "extract the shared block into one module (clone partners in audit.json)";
    case "smells":
      return "replace any-typed identifiers with concrete types";
    case "consistency": {
      const entry = result.lanes.consistency?.entries.find(
        (e) => e.path === path,
      );
      if (entry?.copyArtifactOf)
        return `merge back into \`${entry.copyArtifactOf}\` or delete the copy`;
      if (entry?.orphan) return "verify unreachable, then delete";
      if (entry?.minorityOf)
        return `migrate to the package's majority provider (${entry.minorityOf})`;
      if (entry?.cycleSize) return "break the import cycle";
      return "align with the repo's dominant convention";
    }
    default:
      return "inspect and decide";
  }
}

function verdictCommands(offender: FileScore): string[] {
  return offender.firingLanes.map(
    (f) =>
      `vibecheck wontfix|noise|justify "${f.lane}:${offender.path}" --reason "..."`,
  );
}

/**
 * High-confidence deletion candidates: below-gate singles included —
 * deletion is the one action where a single strong state signal
 * (verified orphan, whole-file dead) is directly actionable.
 */
export function deletionCandidates(
  result: AuditRunResult,
): { path: string; reason: string }[] {
  const out = new Map<string, string>();
  for (const entry of result.lanes.consistency?.entries ?? []) {
    if (entry.orphan) {
      out.set(entry.path, "orphaned — zero import fan-in, no declared entry point");
    }
  }
  for (const entry of result.lanes.deadcode?.entries ?? []) {
    if (entry.unusedFile) {
      out.set(
        entry.path,
        (out.has(entry.path) ? out.get(entry.path) + "; " : "") +
          "knip: entire file unreferenced",
      );
    }
  }
  const suppressed = new Set(
    result.ledger.suppressed.map((s) => s.fingerprint.split(":").slice(1).join(":")),
  );
  return [...out.entries()]
    .filter(([path]) => !suppressed.has(path))
    .map(([path, reason]) => ({ path, reason }))
    .sort((a, b) => (a.path < b.path ? -1 : 1));
}

export function renderAgentBriefing(result: AuditRunResult): string {
  const lines: string[] = [
    "# vibeCheck Audit — agent briefing",
    "",
    `Anchor: \`${result.anchorSha?.slice(0, 12) ?? "no git"}\` (${result.trends.entry.at.slice(0, 10)}). ` +
      "Generated with the audit report; findings below are corroborated by ≥2 independent lanes unless marked otherwise.",
    "",
    "## Ground rules",
    "",
    "- Fixes need no ceremony: land a commit touching a flagged file and the next audit stamps it `fixed` automatically. Partial progress shows as **improving**.",
    "- Findings you judge wrong get verdicts, not workarounds — the commands are attached to each finding. Verdicts are maintainer decisions; confirm with the human before filing one.",
    "- Do not delete anything without the verification step listed on the finding.",
  ];

  for (const [lane, rate] of Object.entries(result.saturatedLanes)) {
    lines.push(
      `- Trust note: the ${lane} lane is repo-saturated (${Math.round(rate * 100)}% firing) and muted from corroboration this run.`,
    );
  }

  const ordered = [
    ...result.bestFirstTargets,
    ...result.worstOffenders.filter(
      (o) => !result.bestFirstTargets.some((t) => t.path === o.path),
    ),
  ];
  if (ordered.length > 0) {
    lines.push("", "## Work items (execution order: smallest blast radius first)");
    for (const [index, offender] of ordered.entries()) {
      lines.push(
        "",
        `### ${index + 1}. \`${offender.path}\``,
        "",
        `- Firing: ${offender.firingLanes.map((f) => f.lane).join(" + ")} (${offender.applicableLanes.length} lanes applicable)`,
      );
      for (const firing of offender.firingLanes) {
        lines.push(
          `- ${firing.lane}: ${laneAction(result, firing.lane, offender.path)}`,
        );
      }
      lines.push(`- If wrong or accepted: \`${verdictCommands(offender)[0]}\``);
    }
  } else {
    lines.push("", "## Work items", "", "None — nothing passes the gate.");
  }

  const deletions = deletionCandidates(result);
  if (deletions.length > 0) {
    lines.push(
      "",
      "## Deletion candidates (single-signal, verify before acting)",
      "",
      "Below-gate but directly actionable once verified. Verification = repo-wide search for string references, dynamic imports, and runner configs.",
      "",
    );
    for (const d of deletions) {
      lines.push(`- \`${d.path}\` — ${d.reason}`);
    }
  }

  lines.push(
    "",
    "## Machine data",
    "",
    "`.vibecheck/out/audit.json` carries full lane entries, clone partners, scores, and ledger state.",
  );
  return lines.join("\n") + "\n";
}
